name: ground54321
description: A grounding technique guide using Flutter.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  speech_to_text: ^6.4.1
  printing: ^5.11.0
  vibration: ^1.8.4
  path_provider: ^2.1.2
  audioplayers: ^5.2.1
  flutter_svg: ^2.0.10


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_test: ^0.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/chime.mp3
